web:
  build: .
  command: /run.sh
  ports:
    - "80:80"
  volumes:
    - ./app:/app
  links:
    - mysql
mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: UnSecUr3dPassW0rd!
    MYSQL_DATABASE: generatedata
